### ISSUE TITLE
Remove scrollbar?

### ISSUE THREAD

**Issue by drsjb80** [DeltaOS2/darksky.widget#3]
Hi. First, love the widget! I'm getting a scrollbar on the right-hand side; I tried adding "overflow hidden" to the CSS but that didn't help. I'm happy to look further - can you point me to what to try? Thanks!

**Comment by Marco-Christiani** [comment]
Same issue here, resolved it by editing weather class `line 393`:
```
.weather
    border 1px solid #4f4f4f
    border-radius 20px
    background rgba(#000, .2)
    /* overflow-y scroll; */ <-- Comment this out
    padding .5rem
```

**Comment by drsjb80** [comment]
Nice! Worked for me. Thanks.
